[project]
name = "nextflow-impl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rujinlong", email = "jinlongru@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "pysam>=0.23.3",
]

[project.scripts]
nextflow-impl = "nextflow_impl:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
